acceptOnlyEncryptedData: false
active: true
errorList: []
fileUpload:
  allowFileUploadFields:
    - files
  enable: false
  validations: {}
guid: 01KDQFQ0D7RG395ERE76A800W8
name: products
path: /products
resetCacheOnModificationOf: []
runOnNativeProcess: null
separateSandboxSettings: null
swaggerDocs: null
versions:
  - isActive: true
    name: Original
    postHooks: []
    preHooks: []
    version: "-1"
