acceptOnlyEncryptedData: false
active: true
errorList: []
fileUpload:
  allowFileUploadFields:
    - files
  enable: false
  validations: {}
guid: 01KG9A9AG4KJ1H17AYGN35T8H7
name: Products export
path: /products_export
resetCacheOnModificationOf: []
runOnNativeProcess: null
separateSandboxSettings: null
swaggerDocs: null
versions:
  - isActive: true
    name: Original
    postHooks: []
    preHooks: []
    version: "-1"
